name: Build and publish docker containers

permissions:
  contents: read
  packages: write

on:
  workflow_call:

jobs:
  build_docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - context: .
            image: file2llm
            file: Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 'Build Docker Image'
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.context }}
          file: ./${{ matrix.context }}/${{ matrix.file }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/opengs/${{ matrix.image }}:latest
            ghcr.io/opengs/${{ matrix.image }}:${{ github.ref_name }}