name: Release new version

permissions:
  contents: write

on:
  push:
    tags:
      - v*

jobs:
  tests:
    name: Test
    uses: ./.github/workflows/test.yml

  release:
    name: Create Release
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2