name: Release new version

permissions:
  contents: write
  packages: write

on:
  push:
    tags:
      - v*

jobs:
  tests:
    name: Test
    uses: ./.github/workflows/test.yml

  release-docker-images:
    needs: [tests]
    name: Release Docker Images
    uses: ./.github/workflows/build-docker.yml

  release:
    name: Create Release
    needs: [release-docker-images]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2