name: Run Tests
on:
  push:
    branches:
      - '**' #ignore tags, because tags will be tested using workflow_call during the release workflow
  workflow_call:

jobs:
  test_all:
    runs-on: ubuntu-latest
    services:
      pgvector:
        image: pgvector/pgvector:0.8.0-pg17
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      ollama:
        image: ollama/ollama:0.6.6
        ports:
          - 11434:11434
        options: >-
          --health-cmd="curl -f http://localhost:11434 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install libraries
        run: |
          sudo apt update
          sudo apt install -y libpng-dev libjpeg-dev libtiff-dev libtesseract-dev tesseract-ocr poppler-utils libpoppler-dev libpoppler-glib-dev libcairo2 libcairo2-dev

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.0

      - name: Download dependencies
        run: go mod download

      - name: Run Tests
        env:
          TEST_EMBEDDER_OLLAMA_BASEURL: http://ollama:11434/api
          TEST_STORAGE_PGVECTOR_DBURL: postgresql://postgres:postgres@pgvector:5432/postgres
        run: go test --tags=file2llm_feature_tesseract,file2llm_feature_pdf,test ./...